/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BuildId = string;
export interface BuildShowcase {
  'id' : BuildId,
  'title' : string,
  'authorId' : UserId,
  'createdAt' : bigint,
  'description' : string,
  'specs' : string,
  'images' : Array<ExternalBlob>,
}
export interface Comment {
  'id' : CommentId,
  'authorId' : UserId,
  'createdAt' : bigint,
  'text' : string,
  'postId' : PostId,
}
export type CommentId = string;
export interface Event {
  'id' : EventId,
  'title' : string,
  'date' : bigint,
  'description' : string,
  'organizerId' : UserId,
  'image' : [] | [ExternalBlob],
  'attendeesCount' : bigint,
  'location' : string,
}
export type EventId = string;
export type ExternalBlob = Uint8Array;
export interface LeaderboardUser {
  'postCount' : bigint,
  'username' : string,
  'displayName' : string,
  'followersCount' : bigint,
  'avatar' : [] | [ExternalBlob],
}
export interface MarketplaceListing {
  'id' : MarketplaceListingId,
  'title' : string,
  'authorId' : UserId,
  'createdAt' : bigint,
  'sold' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : string,
  'condition' : { 'new' : null } |
    { 'used' : null },
}
export type MarketplaceListingId = string;
export interface Message {
  'id' : MessageId,
  'createdAt' : bigint,
  'text' : string,
  'receiverId' : UserId,
  'senderId' : UserId,
}
export type MessageId = string;
export type PostId = string;
export interface PostRecord {
  'id' : PostId,
  'postType' : PostType,
  'authorId' : UserId,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'reelCategory' : [] | [string],
  'mediaData' : [] | [string],
  'caption' : string,
  'image' : [] | [ExternalBlob],
}
export type PostType = { 'feed' : null } |
  { 'reel' : null } |
  { 'mechanic' : null } |
  { 'build' : null };
export interface User {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'followersCount' : bigint,
  'createdAt' : bigint,
  'profilePicData' : [] | [string],
  'carInfo' : string,
  'followingCount' : bigint,
  'profilePic' : [] | [ExternalBlob],
  'coverPhotoData' : [] | [string],
}
export type UserId = string;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'followersCount' : bigint,
  'createdAt' : bigint,
  'profilePicData' : [] | [string],
  'carInfo' : string,
  'followingCount' : bigint,
  'profilePic' : [] | [ExternalBlob],
  'coverPhotoData' : [] | [string],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'askAutomotiveAssistant' : ActorMethod<[string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'attendEvent' : ActorMethod<[EventId], undefined>,
  'createBuild' : ActorMethod<[string, string, string], BuildId>,
  'createEvent' : ActorMethod<[string, string, string, bigint], EventId>,
  'createListing' : ActorMethod<
    [
      string,
      string,
      string,
      { 'new' : null } |
        { 'used' : null },
      string,
      string,
    ],
    MarketplaceListingId
  >,
  'createPost' : ActorMethod<
    [string, Array<string>, PostType, [] | [string], [] | [string]],
    [] | [PostRecord]
  >,
  'createUser' : ActorMethod<[string, string, string, string], UserId>,
  'deleteListing' : ActorMethod<[MarketplaceListingId], undefined>,
  'deletePost' : ActorMethod<[PostId], undefined>,
  'followUser' : ActorMethod<[UserId], undefined>,
  'getAllBuilds' : ActorMethod<[], Array<BuildShowcase>>,
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  'getAllListings' : ActorMethod<[], Array<MarketplaceListing>>,
  'getAllPosts' : ActorMethod<[], Array<PostRecord>>,
  'getBuild' : ActorMethod<[BuildId], [] | [BuildShowcase]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentCount' : ActorMethod<[PostId], bigint>,
  'getComments' : ActorMethod<[PostId], Array<Comment>>,
  'getEvent' : ActorMethod<[EventId], [] | [Event]>,
  'getFeed' : ActorMethod<[PostType], Array<PostRecord>>,
  'getFollowers' : ActorMethod<[UserId], Array<UserId>>,
  'getFollowing' : ActorMethod<[UserId], Array<UserId>>,
  'getLeaderboard' : ActorMethod<[], Array<LeaderboardUser>>,
  'getLikeCount' : ActorMethod<[PostId], bigint>,
  'getListing' : ActorMethod<[MarketplaceListingId], [] | [MarketplaceListing]>,
  'getMessages' : ActorMethod<[string], Array<Message>>,
  'getPost' : ActorMethod<[PostId], [] | [PostRecord]>,
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isFollowing' : ActorMethod<[UserId], boolean>,
  'likePost' : ActorMethod<[PostId], undefined>,
  'markListingAsSold' : ActorMethod<[MarketplaceListingId], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchListings' : ActorMethod<[string], Array<MarketplaceListing>>,
  'searchReels' : ActorMethod<[string], Array<PostRecord>>,
  'searchUsers' : ActorMethod<[string], Array<User>>,
  'sendMessage' : ActorMethod<[UserId, string], MessageId>,
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  'unlikePost' : ActorMethod<[PostId], undefined>,
  'updateCoverPhoto' : ActorMethod<[[] | [string]], undefined>,
  'updateListing' : ActorMethod<
    [
      MarketplaceListingId,
      string,
      string,
      string,
      { 'new' : null } |
        { 'used' : null },
      string,
      string,
    ],
    undefined
  >,
  'updateProfilePic' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];