/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BuildId = string;
export interface BuildShowcase {
  'id' : BuildId,
  'title' : string,
  'authorId' : UserId,
  'createdAt' : bigint,
  'description' : string,
  'specs' : string,
  'images' : Array<ExternalBlob>,
}
export interface Comment {
  'id' : CommentId,
  'authorId' : UserId,
  'createdAt' : bigint,
  'text' : string,
  'postId' : PostId,
}
export type CommentId = string;
export interface Event {
  'id' : EventId,
  'title' : string,
  'date' : bigint,
  'description' : string,
  'organizerId' : UserId,
  'image' : [] | [ExternalBlob],
  'attendeesCount' : bigint,
  'location' : string,
}
export type EventId = string;
export type ExternalBlob = Uint8Array;
export interface MarketplaceListing {
  'id' : MarketplaceListingId,
  'title' : string,
  'authorId' : UserId,
  'createdAt' : bigint,
  'sold' : boolean,
  'description' : string,
  'imageUrl' : string,
  'category' : string,
  'price' : string,
  'condition' : { 'new' : null } |
    { 'used' : null },
}
export type MarketplaceListingId = string;
export interface Message {
  'id' : MessageId,
  'createdAt' : bigint,
  'text' : string,
  'receiverId' : UserId,
  'senderId' : UserId,
}
export type MessageId = string;
export type PostId = string;
export interface PostRecord {
  'id' : PostId,
  'postType' : PostType,
  'authorId' : UserId,
  'createdAt' : bigint,
  'tags' : Array<string>,
  'reelCategory' : [] | [string],
  'caption' : string,
  'image' : [] | [ExternalBlob],
}
export type PostType = { 'feed' : null } |
  { 'reel' : null } |
  { 'mechanic' : null } |
  { 'build' : null };
export interface User {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'followersCount' : bigint,
  'createdAt' : bigint,
  'profilePicData' : [] | [string],
  'carInfo' : string,
  'followingCount' : bigint,
  'profilePic' : [] | [ExternalBlob],
}
export type UserId = string;
export interface UserProfile {
  'id' : UserId,
  'bio' : string,
  'username' : string,
  'displayName' : string,
  'followersCount' : bigint,
  'createdAt' : bigint,
  'profilePicData' : [] | [string],
  'carInfo' : string,
  'followingCount' : bigint,
  'profilePic' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  /**
   * / Add a comment; authorId is derived from the caller's stored profile
   */
  'addComment' : ActorMethod<[PostId, string], CommentId>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Mark attendance for an event (authenticated users only)
   */
  'attendEvent' : ActorMethod<[EventId], undefined>,
  /**
   * / Create a build showcase (authenticated users only)
   */
  'createBuild' : ActorMethod<[string, string, string], BuildId>,
  /**
   * / Create an event (authenticated users only)
   */
  'createEvent' : ActorMethod<[string, string, string, bigint], EventId>,
  /**
   * / Create a marketplace listing
   */
  'createListing' : ActorMethod<
    [
      string,
      string,
      string,
      { 'new' : null } |
        { 'used' : null },
      string,
      string,
    ],
    MarketplaceListingId
  >,
  /**
   * / Create a post; authorId is derived from the caller's stored profile
   */
  'createPost' : ActorMethod<
    [string, Array<string>, PostType, [] | [string]],
    PostId
  >,
  /**
   * / Create a user record (authenticated users only)
   */
  'createUser' : ActorMethod<[string, string, string, string], UserId>,
  /**
   * / Delete a listing (author only)
   */
  'deleteListing' : ActorMethod<[MarketplaceListingId], undefined>,
  /**
   * / Delete post (author only)
   */
  'deletePost' : ActorMethod<[PostId], undefined>,
  /**
   * / Follow another user; followerId is derived from the caller's profile
   */
  'followUser' : ActorMethod<[UserId], undefined>,
  /**
   * / Get all build showcases (public read)
   */
  'getAllBuilds' : ActorMethod<[], Array<BuildShowcase>>,
  /**
   * / Get all events (public read)
   */
  'getAllEvents' : ActorMethod<[], Array<Event>>,
  /**
   * / Get all listings (public read)
   */
  'getAllListings' : ActorMethod<[], Array<MarketplaceListing>>,
  /**
   * / Get all posts (public read)
   */
  'getAllPosts' : ActorMethod<[], Array<PostRecord>>,
  /**
   * / Get a single build showcase (public read)
   */
  'getBuild' : ActorMethod<[BuildId], [] | [BuildShowcase]>,
  /**
   * / Get the caller's own profile
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get all comments for a post (public read)
   */
  'getComments' : ActorMethod<[PostId], Array<Comment>>,
  /**
   * / Get a single event (public read)
   */
  'getEvent' : ActorMethod<[EventId], [] | [Event]>,
  /**
   * / Get feed by post type (public read)
   */
  'getFeed' : ActorMethod<[PostType], Array<PostRecord>>,
  /**
   * / Get the list of users that follow userId (public read)
   */
  'getFollowers' : ActorMethod<[UserId], Array<UserId>>,
  /**
   * / Get the list of users that userId is following (public read)
   */
  'getFollowing' : ActorMethod<[UserId], Array<UserId>>,
  /**
   * / Get like count for a post (public read)
   */
  'getLikeCount' : ActorMethod<[PostId], bigint>,
  /**
   * / Get a single listing (public read)
   */
  'getListing' : ActorMethod<[MarketplaceListingId], [] | [MarketplaceListing]>,
  /**
   * / Get messages in a conversation; caller must be one of the participants
   */
  'getMessages' : ActorMethod<[string], Array<Message>>,
  /**
   * / Get a single post (public read)
   */
  'getPost' : ActorMethod<[PostId], [] | [PostRecord]>,
  /**
   * / Get a user by userId (public read)
   */
  'getUser' : ActorMethod<[UserId], [] | [User]>,
  /**
   * / Get another user's profile (caller must be the user themselves or an admin)
   */
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / Check if caller follows a specific user
   */
  'isFollowing' : ActorMethod<[UserId], boolean>,
  /**
   * / Like a post; userId is derived from the caller's profile
   */
  'likePost' : ActorMethod<[PostId], undefined>,
  /**
   * / Mark a listing as sold (author only)
   */
  'markListingAsSold' : ActorMethod<[MarketplaceListingId], undefined>,
  /**
   * / Save/update the caller's own profile
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  /**
   * / Search listings by title, description, or category (public read)
   */
  'searchListings' : ActorMethod<[string], Array<MarketplaceListing>>,
  /**
   * / Search reels by category or username (authenticated users only)
   */
  'searchReels' : ActorMethod<[string], Array<PostRecord>>,
  /**
   * / Search users by username or display name (public read)
   */
  'searchUsers' : ActorMethod<[string], Array<User>>,
  /**
   * / Send a message; senderId is derived from the caller's profile
   */
  'sendMessage' : ActorMethod<[UserId, string], MessageId>,
  /**
   * / Unfollow a user; followerId is derived from the caller's profile
   */
  'unfollowUser' : ActorMethod<[UserId], undefined>,
  /**
   * / Unlike a post; userId is derived from the caller's profile
   */
  'unlikePost' : ActorMethod<[PostId], undefined>,
  /**
   * / Update a listing (author only)
   */
  'updateListing' : ActorMethod<
    [
      MarketplaceListingId,
      string,
      string,
      string,
      { 'new' : null } |
        { 'used' : null },
      string,
      string,
    ],
    undefined
  >,
  /**
   * / Update the caller's profile picture (base64-encoded image data)
   */
  'updateProfilePic' : ActorMethod<[string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];