/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const PostId = IDL.Text;
export const CommentId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const EventId = IDL.Text;
export const BuildId = IDL.Text;
export const MarketplaceListingId = IDL.Text;
export const PostType = IDL.Variant({
  'feed' : IDL.Null,
  'reel' : IDL.Null,
  'mechanic' : IDL.Null,
  'build' : IDL.Null,
});
export const UserId = IDL.Text;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PostRecord = IDL.Record({
  'id' : PostId,
  'postType' : PostType,
  'authorId' : UserId,
  'createdAt' : IDL.Int,
  'tags' : IDL.Vec(IDL.Text),
  'reelCategory' : IDL.Opt(IDL.Text),
  'mediaData' : IDL.Opt(IDL.Text),
  'caption' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const BuildShowcase = IDL.Record({
  'id' : BuildId,
  'title' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'specs' : IDL.Text,
  'images' : IDL.Vec(ExternalBlob),
});
export const Event = IDL.Record({
  'id' : EventId,
  'title' : IDL.Text,
  'date' : IDL.Int,
  'description' : IDL.Text,
  'organizerId' : UserId,
  'image' : IDL.Opt(ExternalBlob),
  'attendeesCount' : IDL.Nat,
  'location' : IDL.Text,
});
export const MarketplaceListing = IDL.Record({
  'id' : MarketplaceListingId,
  'title' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : IDL.Int,
  'sold' : IDL.Bool,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Text,
  'condition' : IDL.Variant({ 'new' : IDL.Null, 'used' : IDL.Null }),
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'followersCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'profilePicData' : IDL.Opt(IDL.Text),
  'carInfo' : IDL.Text,
  'followingCount' : IDL.Nat,
  'profilePic' : IDL.Opt(ExternalBlob),
  'coverPhotoData' : IDL.Opt(IDL.Text),
});
export const Comment = IDL.Record({
  'id' : CommentId,
  'authorId' : UserId,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'postId' : PostId,
});
export const MessageId = IDL.Text;
export const Message = IDL.Record({
  'id' : MessageId,
  'createdAt' : IDL.Int,
  'text' : IDL.Text,
  'receiverId' : UserId,
  'senderId' : UserId,
});
export const User = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Text,
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'followersCount' : IDL.Nat,
  'createdAt' : IDL.Int,
  'profilePicData' : IDL.Opt(IDL.Text),
  'carInfo' : IDL.Text,
  'followingCount' : IDL.Nat,
  'profilePic' : IDL.Opt(ExternalBlob),
  'coverPhotoData' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'attendEvent' : IDL.Func([EventId], [], []),
  'createBuild' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [BuildId], []),
  'createEvent' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
      [EventId],
      [],
    ),
  'createListing' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'new' : IDL.Null, 'used' : IDL.Null }),
        IDL.Text,
        IDL.Text,
      ],
      [MarketplaceListingId],
      [],
    ),
  'createPost' : IDL.Func(
      [
        IDL.Text,
        IDL.Vec(IDL.Text),
        PostType,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [IDL.Opt(PostRecord)],
      [],
    ),
  'createUser' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [UserId],
      [],
    ),
  'deleteListing' : IDL.Func([MarketplaceListingId], [], []),
  'deletePost' : IDL.Func([PostId], [], []),
  'followUser' : IDL.Func([UserId], [], []),
  'getAllBuilds' : IDL.Func([], [IDL.Vec(BuildShowcase)], ['query']),
  'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getAllListings' : IDL.Func([], [IDL.Vec(MarketplaceListing)], ['query']),
  'getAllPosts' : IDL.Func([], [IDL.Vec(PostRecord)], ['query']),
  'getBuild' : IDL.Func([BuildId], [IDL.Opt(BuildShowcase)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
  'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
  'getEvent' : IDL.Func([EventId], [IDL.Opt(Event)], ['query']),
  'getFeed' : IDL.Func([PostType], [IDL.Vec(PostRecord)], ['query']),
  'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
  'getLikeCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
  'getListing' : IDL.Func(
      [MarketplaceListingId],
      [IDL.Opt(MarketplaceListing)],
      ['query'],
    ),
  'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
  'getPost' : IDL.Func([PostId], [IDL.Opt(PostRecord)], ['query']),
  'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [], []),
  'markListingAsSold' : IDL.Func([MarketplaceListingId], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchListings' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MarketplaceListing)],
      ['query'],
    ),
  'searchReels' : IDL.Func([IDL.Text], [IDL.Vec(PostRecord)], ['query']),
  'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
  'sendMessage' : IDL.Func([UserId, IDL.Text], [MessageId], []),
  'unfollowUser' : IDL.Func([UserId], [], []),
  'unlikePost' : IDL.Func([PostId], [], []),
  'updateCoverPhoto' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
  'updateListing' : IDL.Func(
      [
        MarketplaceListingId,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'new' : IDL.Null, 'used' : IDL.Null }),
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateProfilePic' : IDL.Func([IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const PostId = IDL.Text;
  const CommentId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const EventId = IDL.Text;
  const BuildId = IDL.Text;
  const MarketplaceListingId = IDL.Text;
  const PostType = IDL.Variant({
    'feed' : IDL.Null,
    'reel' : IDL.Null,
    'mechanic' : IDL.Null,
    'build' : IDL.Null,
  });
  const UserId = IDL.Text;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PostRecord = IDL.Record({
    'id' : PostId,
    'postType' : PostType,
    'authorId' : UserId,
    'createdAt' : IDL.Int,
    'tags' : IDL.Vec(IDL.Text),
    'reelCategory' : IDL.Opt(IDL.Text),
    'mediaData' : IDL.Opt(IDL.Text),
    'caption' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const BuildShowcase = IDL.Record({
    'id' : BuildId,
    'title' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'specs' : IDL.Text,
    'images' : IDL.Vec(ExternalBlob),
  });
  const Event = IDL.Record({
    'id' : EventId,
    'title' : IDL.Text,
    'date' : IDL.Int,
    'description' : IDL.Text,
    'organizerId' : UserId,
    'image' : IDL.Opt(ExternalBlob),
    'attendeesCount' : IDL.Nat,
    'location' : IDL.Text,
  });
  const MarketplaceListing = IDL.Record({
    'id' : MarketplaceListingId,
    'title' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : IDL.Int,
    'sold' : IDL.Bool,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Text,
    'condition' : IDL.Variant({ 'new' : IDL.Null, 'used' : IDL.Null }),
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'followersCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'profilePicData' : IDL.Opt(IDL.Text),
    'carInfo' : IDL.Text,
    'followingCount' : IDL.Nat,
    'profilePic' : IDL.Opt(ExternalBlob),
    'coverPhotoData' : IDL.Opt(IDL.Text),
  });
  const Comment = IDL.Record({
    'id' : CommentId,
    'authorId' : UserId,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'postId' : PostId,
  });
  const MessageId = IDL.Text;
  const Message = IDL.Record({
    'id' : MessageId,
    'createdAt' : IDL.Int,
    'text' : IDL.Text,
    'receiverId' : UserId,
    'senderId' : UserId,
  });
  const User = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Text,
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'followersCount' : IDL.Nat,
    'createdAt' : IDL.Int,
    'profilePicData' : IDL.Opt(IDL.Text),
    'carInfo' : IDL.Text,
    'followingCount' : IDL.Nat,
    'profilePic' : IDL.Opt(ExternalBlob),
    'coverPhotoData' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentId], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'attendEvent' : IDL.Func([EventId], [], []),
    'createBuild' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [BuildId], []),
    'createEvent' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Int],
        [EventId],
        [],
      ),
    'createListing' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'new' : IDL.Null, 'used' : IDL.Null }),
          IDL.Text,
          IDL.Text,
        ],
        [MarketplaceListingId],
        [],
      ),
    'createPost' : IDL.Func(
        [
          IDL.Text,
          IDL.Vec(IDL.Text),
          PostType,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [IDL.Opt(PostRecord)],
        [],
      ),
    'createUser' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [UserId],
        [],
      ),
    'deleteListing' : IDL.Func([MarketplaceListingId], [], []),
    'deletePost' : IDL.Func([PostId], [], []),
    'followUser' : IDL.Func([UserId], [], []),
    'getAllBuilds' : IDL.Func([], [IDL.Vec(BuildShowcase)], ['query']),
    'getAllEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getAllListings' : IDL.Func([], [IDL.Vec(MarketplaceListing)], ['query']),
    'getAllPosts' : IDL.Func([], [IDL.Vec(PostRecord)], ['query']),
    'getBuild' : IDL.Func([BuildId], [IDL.Opt(BuildShowcase)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
    'getComments' : IDL.Func([PostId], [IDL.Vec(Comment)], ['query']),
    'getEvent' : IDL.Func([EventId], [IDL.Opt(Event)], ['query']),
    'getFeed' : IDL.Func([PostType], [IDL.Vec(PostRecord)], ['query']),
    'getFollowers' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getFollowing' : IDL.Func([UserId], [IDL.Vec(UserId)], ['query']),
    'getLikeCount' : IDL.Func([PostId], [IDL.Nat], ['query']),
    'getListing' : IDL.Func(
        [MarketplaceListingId],
        [IDL.Opt(MarketplaceListing)],
        ['query'],
      ),
    'getMessages' : IDL.Func([IDL.Text], [IDL.Vec(Message)], ['query']),
    'getPost' : IDL.Func([PostId], [IDL.Opt(PostRecord)], ['query']),
    'getUser' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isFollowing' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [], []),
    'markListingAsSold' : IDL.Func([MarketplaceListingId], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchListings' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MarketplaceListing)],
        ['query'],
      ),
    'searchReels' : IDL.Func([IDL.Text], [IDL.Vec(PostRecord)], ['query']),
    'searchUsers' : IDL.Func([IDL.Text], [IDL.Vec(User)], ['query']),
    'sendMessage' : IDL.Func([UserId, IDL.Text], [MessageId], []),
    'unfollowUser' : IDL.Func([UserId], [], []),
    'unlikePost' : IDL.Func([PostId], [], []),
    'updateCoverPhoto' : IDL.Func([IDL.Opt(IDL.Text)], [], []),
    'updateListing' : IDL.Func(
        [
          MarketplaceListingId,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'new' : IDL.Null, 'used' : IDL.Null }),
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateProfilePic' : IDL.Func([IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };